#!/usr/bin/env bash

set -euo pipefail

DOCKERHUB_REGISTRY=docker.io
ASERV92_REGISTRY=${DOCKERHUB_REGISTRY}/aserv92

DOTNET_SDK_IMAGE_NAME="dotnet-sdk"

DOTNET_SDK_IMAGE_TAG="10.0.105-r0-82c2447"

export DOTNET_SDK_IMAGE="${ASERV92_REGISTRY}/${DOTNET_SDK_IMAGE_NAME}:${DOTNET_SDK_IMAGE_TAG}"
